### ISSUE TITLE
 Could NOT find Festival (missing: Festival_LIBRARIES Festival_INCLUDE_DIR)

### ISSUE THREAD

**Issue by feifeiwei** [homer-robotics/homer_robot_face#1]
hello, 
thanks for you nice work, 
when i catkin_make the project, some mistake happened. could you show me how to solve it?
--------------------------------------------------------------------------------------
CMake Error at /usr/local/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Festival (missing: Festival_LIBRARIES Festival_INCLUDE_DIR)

**Comment by eduardafneumann** [comment]
I'm getting the same error, how did you solved it??

**Comment by arthurdemarchi** [comment]
install festival-dev package, on ubuntu:
apt-get install festival-dev
