### ISSUE TITLE
Could NOT find EST (missing: ESD_LIBRARY)

### ISSUE THREAD

**Issue by feifeiwei** [homer-robotics/homer_robot_face#2]
when i run catkin_make, 

some mistake happened..  splease help me.
Could NOT find EST (missing: ESD_LIBRARY),,,

**Comment by vseib** [comment]
Hello feifeiwei,
EST is a dependency of Festival. I don't know right now which library this is exactly. However, if you search online how to install festival speech synthesis you should find the missing library.
Hope this helps

**Comment by feifeiwei** [comment]
thank you. i have got it.

**Comment by arthurdemarchi** [comment]
I'm having the same problem and cant find which dependency is this, if someone can please name it I would be glad.
