### ISSUE TITLE
what does the topics of /robot_face/ImageDisplay and  /robot_face/ImageFileDisplay mean?  

### ISSUE THREAD

**Issue by feifeiwei** [homer-robotics/homer_robot_face#4]
hello, i want to know how to make it work using the topic of /robot_face/ImageDisplay and  /robot_face/ImageFileDisplay. I don't know the function of these two topics.

**Comment by vseib** [comment]
Hi again,
as far as I remember (and without looking into the code again) the first topic receives an Image to be displayed for a certain time on the screen (instead of the face). The second topic does the same, but requires a path to an image on disc instead of an image message.
Best,
Viktor
